### PR TITLE
Django 4 compatibility

### PR DESCRIPTION
**Pull request by pulse-mind**
Django40 compatibility
* ugettext and smart_text
* deprecation warning on regexp
* TypeError: __init__() got an unexpected keyword argument 'providing_args'
* force_text -> force_str
* urlquote -> urllib.parse.quote()

### CODE REVIEW

**Comment by pulse-mind** [comment]
@smacker Hello,

Thank you for your job. I think everything is fine, it works on my project
I am waiting your this pull request to then doing a push request on django-tinymce4-lite too (it uses this repo)

**Comment by smacker** [comment]
@pulse-mind thank you. The PR looks great. Let me test it locally before merging. I'll try to do it during this Chinese New Year holidays.

**Comment by smacker** [comment]
Looks like you missed the templates. They use `ifequal`/`ifnotequal` tags which were removed in django 4. Also, the index template in django has changed a bit so UI is kind of broken.

Anyway I'm merging this changes and I'll fix the rest in a separate PR.

Thanks again!

**Comment by pulse-mind** [comment]
thank you!

**Pull request merged**
