### PR TITLE
Django 1.10 compatibility

### PR DESCRIPTION
**Pull request by dpaluch-rp**

### CODE REVIEW

**Comment by smacker** [comment]
I didn't run tests, but looks like backward compatibility is broken. Can you make it work for all versions of django? Looks like we just need different render function for django1.10 & all older versions. I put such stuff here: https://github.com/smacker/django-filebrowser-no-grappelli/blob/master/filebrowser/compat.py

**Comment by timgraham** [comment]
This isn't correct. You also need to set `request.current_app` as done in https://github.com/sehmaschine/django-filebrowser/commit/2e9f8d737afbb7da93e4e2fc14947341f0222139. Do you still require supporting unsupported versions of Django or can you pull in the upstream changes? 

FileBrowser 3.7.3 (Development Version for Django = 1.9, see Branch Stable/3.7.x)
FileBrowser 3.6.5 (Development Version for Django = 1.8, see Branch Stable/3.6.x)
FileBrowser 3.5.9 (Development Version for Django <= 1.7, see Branch Stable/3.5.x)

**Comment by timgraham** [comment]
@smacker, could you advise on how you want to proceed? I'd like to update my site to 1.10 before 1.9 support ends in April.

**Comment by smacker** [comment]
@timgraham I'll try to merge upstream and make it compatible with Django 1.10 during Chinese New Year (in next 2 weeks). I'm not sure how to proceed it yet, depends on how many things are broken.

**Comment by smacker** [comment]
django-filebrowser-no-grappelli 3.7.0 released. It supports django 1.8/1.9/1.10

**Pull request closed without merging**
