### PR TITLE
Target Django 1.9

### PR DESCRIPTION
**Pull request by lucacorti**
This makes at least browse work again on 1.9, upload still has javascript errors.

### CODE REVIEW

**Comment by smacker** [comment]
can you fix js errors too? I'm really busy right now and don't have time to fix it ((

**Comment by lucacorti** [comment]
I've committed a few more fixes, fixing jquery scripts, the search icon, output for file extensions which was also breaking JS and removed legacy urlpatterns. I am now able to upload files. If everything is fine, could you make an updated release?

**Comment by lucacorti** [comment]
On;y tested on Django 1.9.1 though.

**Comment by lucacorti** [comment]
Missed a couple jquery script paths. Now fixed.

**Comment by smacker** [comment]
Thanks a lot!!!

It looks like it will be broken with older versions of django. I need to test it first. I'll do it tonight.

**Comment by smacker** [comment]
I tested it. And as I thought it's very broken (. I can't fix all issues fast enough.
I don't want to break all older versions, because of django 1.9.

As a temporary solution you can add dependence from github, not pypy:
```
requirements.txt:
git+git://github.com/lucacorti/django-filebrowser-no-grappelli#egg=django-filebrowser
```

**Comment by smacker** [comment]
fixed

**Pull request closed without merging**
